### ISSUE TITLE
Apply Coding Protocol to Sample 

### ISSUE THREAD

**Issue by nniiicc** [PugetSoundClinic-PIT/OSH_Review#10]
@lindseysschwartz 
- @sarah114tran and I have been working on a scoping review about empirical research conducted on the topic of open-source hardware.
- A draft protocol by @sarah114tran is here: https://docs.google.com/document/d/1ts-VyCGtjB9pwRIShM0HZiSFL5SV-QWaEFAQuvqn-SY/edit - See the section that I left a comment "LS" on which explains the topic categorization we are applying to studies in our sample 
- Here -> https://docs.google.com/spreadsheets/d/1GGzE0qIDeKrOaxUrFpMTOaaNsXrHkODmvqBDLHI9rlM/edit?gid=1590543333#gid=1590543333 you will find a sample of 10 articles to code. Try to identify the type of method used, the main ways data were collected, and then using the topic category (described above) - assign the paper to a category. 
- Don't spend more than 1 hour on this - if something is taking longer or hard to interpret let us know ✌️

**Comment by thin-lizard** [comment]
Done! Happy to discuss if needed. I checked our agreement around the thematic categories (Communities, Diffusion, etc.) and left notes in the "LS_10" sheet
