### ISSUE TITLE
Skeleton for OSH Scoping Review

### ISSUE THREAD

**Issue by sarah114tran** [PugetSoundClinic-PIT/OSH_Review#11]
Here is the link for the rough draft for the systematic review on OSH: https://docs.google.com/document/d/1I_qxMUAmuoM6wEvnNB3V189bKL2A0mZ_rw2qgxD4x-M/edit?usp=sharing
```[tasklist]
### Tasks
```

**Comment by nniiicc** [comment]
@nniiicc - Review the skeleton above
