### ISSUE TITLE
Research Meeting: 09.24.2024

### ISSUE THREAD

**Issue by nniiicc** [PugetSoundClinic-PIT/OSH_Review#12]
**Gigplat** discussion: two issues (1) Update ABD paper (2) Pilot / validate a scale for psychometrics related to distributional, procedural, and informational justice... 

- Re 1: Awareness: Procedural justice::Access: Distributional justice - if we agree then lets discuss if collecting a new round of data from people who should have been subject of settlement can help us make the paper more relevant... 
- Re 2: If we decide to update the data with this in mind - we should have a pre-interiew quesitonnaire that asks some questions from our scale survey, and also mix-in our survey questions at the actual interview 
- Re 2: If we decide NOT to update the ABD paper in this way then should we go back to our participant pool for piloting / validating the scale? 

**Decisions we need to record:**
- [x] Plan for updating the ABD paper: Update scope, timeline, outlet (options: [Regulation and governance](https://onlinelibrary.wiley.com/journal/17485991); [Platforms & Society ](https://journals.sagepub.com/home/PNS); or [ACM Journal of Responsible Computing](https://dl.acm.org/journal/jrc)
- [ ] Plan for piloting the scale:  @sarah114tran - give us next steps on the scale development, giving feedback, etc. 

**OSH** we need to do three things (1) Review the goals of the Project (2) Status update on OSH review (3) Discuss interest in future studies 

- Re 1: When LS starts on 10.01 we will have a research meeting and go into depth about goals, open-source, research agendas around this topic, etc. For now some key sources:
- - This repository (obv) should coordinate all work on the OSH review... Subsequent repos should be named OSH_X and tagged with the project name (OSH) 
- - We have a google drive https://drive.google.com/drive/u/1/folders/1SxXNpmhs_PfjQXWO5kUoo75KTvWXyEJj 
- Re 2: The goal is to produce a scoping review for empirical OSH research (👋 wave hands at definitions for now)... here is what we have 
- - [Protocol ](https://docs.google.com/document/d/1ts-VyCGtjB9pwRIShM0HZiSFL5SV-QWaEFAQuvqn-SY/edit)
- - [5th round of co-coding](https://docs.google.com/spreadsheets/d/1GGzE0qIDeKrOaxUrFpMTOaaNsXrHkODmvqBDLHI9rlM/edit?gid=1590543333#gid=1590543333)
- - [Skeleton for paper](https://docs.google.com/document/d/1I_qxMUAmuoM6wEvnNB3V189bKL2A0mZ_rw2qgxD4x-M/edit#heading=h.e0do1lazmb7j) that we will submit to Journal of Open Source Hardware (5k word limit 🤌) 
- Re 3: This quarter we are each going to each lead small(ish) scale studies. I have some ideas that I would like us to execute, but overall you will be more productive if you care about what you are doing... So here are some ideas that we should decide on soon:
- - OSH in Science: We start from publications and journals, and then locate linked software, documentation, etc - this would be primarily a scientometric (quantative) study
- - OSH Certifications and Quality: We build a project from the databases that record certifications https://certification.oshwa.org/list.html (this could be about, for example, supply chain issues, sustainability, etc) 
- RISC-V open source chips: This starts to blur the line between software and hardware, but chips are the new data in terms of scarce resources enabling technological innovation... As a result there is a huge intense focus on the chip manufacturing and procurement process for science & technology policy. Relatively few people are paying attention to open-source instruction sets like RISC-V which means we could do a lot of very high impact work that has policy implications if we dive into this area https://en.wikipedia.org/wiki/RISC-V 
- OSH licensing - relatively little written about this 
- Right to repair legislation - relatively little research from social scientists on this area of the law 
- Another option might be a smaller case study that is mixed methods focusing on a particular OSH project like https://ojs.lib.uwo.ca/index.php/openhardware/article/view/17863

**Decisions we need to make today:** 
- [x] Next steps on OSH Review
- [x] General areas of interest for designing projects related to OSH Autumn quarter

**Comment by nniiicc** [comment]
GigPlat 

- [ ] @nniiicc - Write outline for ABD new draft - including how we make a shift towards interpreting experiences of ICs as about injustice (DJ, PJ) 
- @lindseysschwartz & @sarah114tran - incorporate some DJ and PJ literature in the discussion section, and create a description of the main empirical and theoretical contributions (don't include in the narrative yet, but circulate a draft or outline and then we can write it up) 
- @lindseysschwartz - in a repo issue describe P&S requirements for publication (word length etc)

**Comment by thin-lizard** [comment]
- [x] @lindseysschwartz  - make new repo for just this paper
- [ ] @lindseysschwartz - set timeline & deadline

**Comment by nniiicc** [comment]
Lindsey - created the repo and assigned issues:
-  https://github.com/PugetSoundClinic-PIT/abd/issues/3 
- https://github.com/PugetSoundClinic-PIT/abd/issues/5
