### ISSUE TITLE
Repo / Docs Clean up

### ISSUE THREAD

**Issue by nniiicc** [PugetSoundClinic-PIT/OSH_Review#14]
@sarah114tran & @lindseysschwartz 

I would like to clean up some of the floating drafts and documents related to this project. Spend 1 hour locating and linking all our documentation... You could do this as an index document in google docs, an issue in this repo, or a wiki in this repo... Just make it so that whatever we do is sustainable 

Here are some resources to be sure to include 
- OSH drive folder https://drive.google.com/drive/u/1/folders/1SxXNpmhs_PfjQXWO5kUoo75KTvWXyEJj (@sarah114tran - be sure to move all of the documents created under your account to this folder) 
- Link to Zotero group 
- Links to all protocols and coding 
- Links to paper draft 
- Link to outlet for OSH review

**Comment by nniiicc** [comment]
@lindseysschwartz & @sarah114tran 

A few additional requests 
- Document what you decided - where are these links supposed to live (looks like a wiki?) 
- Clean up file names - it is hard to tell what the google drive contains. A good rule of thumb for file naming is to use the project/study name and a description "OSH_Protocol" "OSH_LitCodingRd2" etc 
- If you use markdown - please create readable links (e.g. use the `[My Link Text](www.mylink.com)` syntax 
- When you're done working on this please close the issue

**Comment by sarah114tran** [comment]
Hi @nniiicc

I've updated the Wiki and the file names. Let me know if you would like any additional edits, and then I will close the issue!
