### ISSUE TITLE
Qual analysis of corpus -

### ISSUE THREAD

**Issue by thin-lizard** [PugetSoundClinic-PIT/OSH_Review#20]
Qual analysis to answer Qs like:
    - What are important findings from this body / these categories of literature
    - What does this teach us 
    - What are the data sources for quant papers
    - Potential role of applying / adapting CHAOSS https://chaoss.community/ to OSH
 
Eg:
  - here is a paper where they talk about open questions in OSH: https://hal.science/hal-03395460v1/file/seven-observations-and-research-questions-about-open-design-and-open-source-hardware.pdf  - We might be able to say whether these are, for example, still open questions, not good questions, etc
  - here is a cscw preprint about OSH - see section 5.3 where they say there are implications for OSH empirical researchers https://arxiv.org/html/2406.12801v1#bib.bib21

**Comment by thin-lizard** [comment]
We'll each have an open google doc for notetaking and leave comments for each other as needed:

Elements to look at in each paper (non-exhaustive list): 
- Key findings & concepts
- Sample size (n=?)
- Methods
- Limitations (as stated by authors)
- Future work (as stated by authors)
- Settings for OSH (There are different sectors / applications of OSH - DIY hacker enthusiasts; people doing scientific instrumentation; civic-based; public health; industry; accessibility computing -- there may be gaps in application space)

**Comment by nniiicc** [comment]
@lindseysschwartz @sarah114tran  - Please meet, discuss, and complete this issue.
