### ISSUE TITLE
Cleaning steps

### ISSUE THREAD

**Issue by nniiicc** [PugetSoundClinic-PIT/OSH_Review#6]
@sarah114tran - documenting data collection and some preliminary cleaning of the dataset here. 

Two new directories in the repo:
- Data - contains all data collected. 
- Code - Scripts used to clean the data

Next steps:
- Combine the dataset titled `dedup_clean.csv`with our previously coded dataset from ASReview (where we agreed on what to include and not include)
- Reingest to ASReview
- Begin coding again with our strict criteria on what counts for empirical: 
- - Report results about OSH (and not OSS for example) 
- - Uses method that is repeatable or quasi-scientific (e.g. case study, survey, statistical analysis, etc) 

--- 

Query: 
- ("open-source hardware" OR "open source hardware" OR "open hardware")
- Web of Science - 774 (1000)
- Crossref 1000 (1000) 
- Scopus 200 (200) 
- Semantic Scholar 1000 (1000)
- Google Scholar 370 (500)* 

For Google Scholar query:
- ("open-source hardware" OR "open source hardware" OR "open hardware") AND "empirical" 

Total of 3474 observations 

**Applying inclusions and exclusion criteria**

Date
Removed out of range - 661

Deduplication: 
Original number of rows: 2813
Number of duplicates identified by title: 959
Number of rows after title de-duplication: 2241
Number of duplicates identified by DOI: 473
Final number of rows after DOI de-duplication: 1802

Crossref does not allow for search by type... so clean by type (removed following)
- 5 - PDF notes 
- 20 REVIEWS
- 6 REPORTS 
- 58 pre-prints
- 3 abstracts
- 1 grant 
- 7 support materials 
- 7 datasets 

Final dataset: 1692

**Comment by sarah114tran** [comment]
@nniiicc -- I have decided to drop all of the articles with empty abstracts, because it can be hard to tell with just title **will document in the coding notes/protocol** I would drop the null values in the in the "abstract" column in the dedup_clean.csv before combining it with your previously coded dataset, because the capitalization of each column label in not exact in both datasets.
